// @license
// Copyright (c) Audanika
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by ffigen from ffigen.yaml. Do not edit.
// coverage:ignore-file
// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// The NDK AMidi API, libamidi.so, API 29 and later.
class MidiAndroidAMidiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MidiAndroidAMidiBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MidiAndroidAMidiBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int AMidiDevice_fromJava(
    ffi.Pointer<JNIEnv> env,
    jobject midiDeviceObj,
    ffi.Pointer<ffi.Pointer<AMidiDevice>> outDevicePtrPtr,
  ) {
    return _AMidiDevice_fromJava(env, midiDeviceObj, outDevicePtrPtr);
  }

  late final _AMidiDevice_fromJavaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<JNIEnv>,
            jobject,
            ffi.Pointer<ffi.Pointer<AMidiDevice>>,
          )
        >
      >('AMidiDevice_fromJava');
  late final _AMidiDevice_fromJava =
      _AMidiDevice_fromJavaPtr.asFunction<
        int Function(
          ffi.Pointer<JNIEnv>,
          jobject,
          ffi.Pointer<ffi.Pointer<AMidiDevice>>,
        )
      >();

  int AMidiDevice_getDefaultProtocol(ffi.Pointer<AMidiDevice> device) {
    return _AMidiDevice_getDefaultProtocol(device);
  }

  late final _AMidiDevice_getDefaultProtocolPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AMidiDevice>)>>(
        'AMidiDevice_getDefaultProtocol',
      );
  late final _AMidiDevice_getDefaultProtocol =
      _AMidiDevice_getDefaultProtocolPtr.asFunction<
        int Function(ffi.Pointer<AMidiDevice>)
      >();

  int AMidiDevice_getNumInputPorts(ffi.Pointer<AMidiDevice> device) {
    return _AMidiDevice_getNumInputPorts(device);
  }

  late final _AMidiDevice_getNumInputPortsPtr =
      _lookup<ffi.NativeFunction<ssize_t Function(ffi.Pointer<AMidiDevice>)>>(
        'AMidiDevice_getNumInputPorts',
      );
  late final _AMidiDevice_getNumInputPorts =
      _AMidiDevice_getNumInputPortsPtr.asFunction<
        int Function(ffi.Pointer<AMidiDevice>)
      >();

  int AMidiDevice_getNumOutputPorts(ffi.Pointer<AMidiDevice> device) {
    return _AMidiDevice_getNumOutputPorts(device);
  }

  late final _AMidiDevice_getNumOutputPortsPtr =
      _lookup<ffi.NativeFunction<ssize_t Function(ffi.Pointer<AMidiDevice>)>>(
        'AMidiDevice_getNumOutputPorts',
      );
  late final _AMidiDevice_getNumOutputPorts =
      _AMidiDevice_getNumOutputPortsPtr.asFunction<
        int Function(ffi.Pointer<AMidiDevice>)
      >();

  int AMidiDevice_getType(ffi.Pointer<AMidiDevice> device) {
    return _AMidiDevice_getType(device);
  }

  late final _AMidiDevice_getTypePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<AMidiDevice>)>>(
        'AMidiDevice_getType',
      );
  late final _AMidiDevice_getType =
      _AMidiDevice_getTypePtr.asFunction<
        int Function(ffi.Pointer<AMidiDevice>)
      >();

  int AMidiDevice_release(ffi.Pointer<AMidiDevice> midiDevice) {
    return _AMidiDevice_release(midiDevice);
  }

  late final _AMidiDevice_releasePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<AMidiDevice>)>>(
        'AMidiDevice_release',
      );
  late final _AMidiDevice_release =
      _AMidiDevice_releasePtr.asFunction<
        int Function(ffi.Pointer<AMidiDevice>)
      >();

  void AMidiInputPort_close(ffi.Pointer<AMidiInputPort> inputPort) {
    return _AMidiInputPort_close(inputPort);
  }

  late final _AMidiInputPort_closePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<AMidiInputPort>)>
      >('AMidiInputPort_close');
  late final _AMidiInputPort_close =
      _AMidiInputPort_closePtr.asFunction<
        void Function(ffi.Pointer<AMidiInputPort>)
      >();

  int AMidiInputPort_open(
    ffi.Pointer<AMidiDevice> device,
    int portNumber,
    ffi.Pointer<ffi.Pointer<AMidiInputPort>> outInputPortPtr,
  ) {
    return _AMidiInputPort_open(device, portNumber, outInputPortPtr);
  }

  late final _AMidiInputPort_openPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<AMidiDevice>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<AMidiInputPort>>,
          )
        >
      >('AMidiInputPort_open');
  late final _AMidiInputPort_open =
      _AMidiInputPort_openPtr.asFunction<
        int Function(
          ffi.Pointer<AMidiDevice>,
          int,
          ffi.Pointer<ffi.Pointer<AMidiInputPort>>,
        )
      >();

  int AMidiInputPort_send(
    ffi.Pointer<AMidiInputPort> inputPort,
    ffi.Pointer<ffi.Uint8> buffer,
    int numBytes,
  ) {
    return _AMidiInputPort_send(inputPort, buffer, numBytes);
  }

  late final _AMidiInputPort_sendPtr =
      _lookup<
        ffi.NativeFunction<
          ssize_t Function(
            ffi.Pointer<AMidiInputPort>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
          )
        >
      >('AMidiInputPort_send');
  late final _AMidiInputPort_send =
      _AMidiInputPort_sendPtr.asFunction<
        int Function(ffi.Pointer<AMidiInputPort>, ffi.Pointer<ffi.Uint8>, int)
      >();

  int AMidiInputPort_sendFlush(ffi.Pointer<AMidiInputPort> inputPort) {
    return _AMidiInputPort_sendFlush(inputPort);
  }

  late final _AMidiInputPort_sendFlushPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<AMidiInputPort>)>
      >('AMidiInputPort_sendFlush');
  late final _AMidiInputPort_sendFlush =
      _AMidiInputPort_sendFlushPtr.asFunction<
        int Function(ffi.Pointer<AMidiInputPort>)
      >();

  int AMidiInputPort_sendWithTimestamp(
    ffi.Pointer<AMidiInputPort> inputPort,
    ffi.Pointer<ffi.Uint8> buffer,
    int numBytes,
    int timestamp,
  ) {
    return _AMidiInputPort_sendWithTimestamp(
      inputPort,
      buffer,
      numBytes,
      timestamp,
    );
  }

  late final _AMidiInputPort_sendWithTimestampPtr =
      _lookup<
        ffi.NativeFunction<
          ssize_t Function(
            ffi.Pointer<AMidiInputPort>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Int64,
          )
        >
      >('AMidiInputPort_sendWithTimestamp');
  late final _AMidiInputPort_sendWithTimestamp =
      _AMidiInputPort_sendWithTimestampPtr.asFunction<
        int Function(
          ffi.Pointer<AMidiInputPort>,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
        )
      >();

  void AMidiOutputPort_close(ffi.Pointer<AMidiOutputPort> outputPort) {
    return _AMidiOutputPort_close(outputPort);
  }

  late final _AMidiOutputPort_closePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<AMidiOutputPort>)>
      >('AMidiOutputPort_close');
  late final _AMidiOutputPort_close =
      _AMidiOutputPort_closePtr.asFunction<
        void Function(ffi.Pointer<AMidiOutputPort>)
      >();

  int AMidiOutputPort_open(
    ffi.Pointer<AMidiDevice> device,
    int portNumber,
    ffi.Pointer<ffi.Pointer<AMidiOutputPort>> outOutputPortPtr,
  ) {
    return _AMidiOutputPort_open(device, portNumber, outOutputPortPtr);
  }

  late final _AMidiOutputPort_openPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<AMidiDevice>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<AMidiOutputPort>>,
          )
        >
      >('AMidiOutputPort_open');
  late final _AMidiOutputPort_open =
      _AMidiOutputPort_openPtr.asFunction<
        int Function(
          ffi.Pointer<AMidiDevice>,
          int,
          ffi.Pointer<ffi.Pointer<AMidiOutputPort>>,
        )
      >();

  int AMidiOutputPort_receive(
    ffi.Pointer<AMidiOutputPort> outputPort,
    ffi.Pointer<ffi.Int32> opcodePtr,
    ffi.Pointer<ffi.Uint8> buffer,
    int maxBytes,
    ffi.Pointer<ffi.Size> numBytesReceivedPtr,
    ffi.Pointer<ffi.Int64> outTimestampPtr,
  ) {
    return _AMidiOutputPort_receive(
      outputPort,
      opcodePtr,
      buffer,
      maxBytes,
      numBytesReceivedPtr,
      outTimestampPtr,
    );
  }

  late final _AMidiOutputPort_receivePtr =
      _lookup<
        ffi.NativeFunction<
          ssize_t Function(
            ffi.Pointer<AMidiOutputPort>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Int64>,
          )
        >
      >('AMidiOutputPort_receive');
  late final _AMidiOutputPort_receive =
      _AMidiOutputPort_receivePtr.asFunction<
        int Function(
          ffi.Pointer<AMidiOutputPort>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Int64>,
        )
      >();
}

const int AMIDI_DEVICE_TYPE_BLUETOOTH = 3;

const int AMIDI_DEVICE_TYPE_USB = 1;

const int AMIDI_DEVICE_TYPE_VIRTUAL = 2;

const int AMIDI_OPCODE_DATA = 1;

const int AMIDI_OPCODE_FLUSH = 2;

final class AMidiDevice extends ffi.Opaque {}

sealed class AMidiDevice_Protocol {
  static const AMIDI_DEVICE_PROTOCOL_UMP_USE_MIDI_CI = 0;
  static const AMIDI_DEVICE_PROTOCOL_UMP_MIDI_1_0_UP_TO_64_BITS = 1;
  static const AMIDI_DEVICE_PROTOCOL_UMP_MIDI_1_0_UP_TO_64_BITS_AND_JRTS = 2;
  static const AMIDI_DEVICE_PROTOCOL_UMP_MIDI_1_0_UP_TO_128_BITS = 3;
  static const AMIDI_DEVICE_PROTOCOL_UMP_MIDI_1_0_UP_TO_128_BITS_AND_JRTS = 4;
  static const AMIDI_DEVICE_PROTOCOL_UMP_MIDI_2_0 = 17;
  static const AMIDI_DEVICE_PROTOCOL_UMP_MIDI_2_0_AND_JRTS = 18;
  static const AMIDI_DEVICE_PROTOCOL_UNKNOWN = -1;
}

final class AMidiInputPort extends ffi.Opaque {}

final class AMidiOutputPort extends ffi.Opaque {}

typedef JNIEnv = ffi.Pointer<JNINativeInterface>;
typedef JNIEnv$1 = ffi.Pointer<JNINativeInterface>;

final class JNIInvokeInterface extends ffi.Opaque {}

final class JNINativeInterface extends ffi.Opaque {}

typedef JavaVM = ffi.Pointer<JNIInvokeInterface>;
typedef JavaVM$1 = ffi.Pointer<JNIInvokeInterface>;
typedef __builtin_va_list = __va_list;
typedef __kernel_long_t = ffi.Long;
typedef Dart__kernel_long_t = int;
typedef __kernel_ssize_t = __kernel_long_t;

final class __va_list extends ffi.Opaque {}

final class _jfieldID extends ffi.Opaque {}

final class _jmethodID extends ffi.Opaque {}

typedef jarray = jobject;
typedef jboolean = ffi.Uint8;
typedef Dartjboolean = int;
typedef jbooleanArray = jarray;
typedef jbyte = ffi.Int8;
typedef Dartjbyte = int;
typedef jbyteArray = jarray;
typedef jchar = ffi.Uint16;
typedef Dartjchar = int;
typedef jcharArray = jarray;
typedef jclass = jobject;
typedef jdouble = ffi.Double;
typedef Dartjdouble = double;
typedef jdoubleArray = jarray;
typedef jfieldID = ffi.Pointer<_jfieldID>;
typedef jfloat = ffi.Float;
typedef Dartjfloat = double;
typedef jfloatArray = jarray;
typedef jint = ffi.Int32;
typedef Dartjint = int;
typedef jintArray = jarray;
typedef jlong = ffi.Int64;
typedef Dartjlong = int;
typedef jlongArray = jarray;
typedef jmethodID = ffi.Pointer<_jmethodID>;
typedef jobject = ffi.Pointer<ffi.Void>;
typedef jobjectArray = jarray;

sealed class jobjectRefType {
  static const JNIInvalidRefType = 0;
  static const JNILocalRefType = 1;
  static const JNIGlobalRefType = 2;
  static const JNIWeakGlobalRefType = 3;
}

typedef jshort = ffi.Int16;
typedef Dartjshort = int;
typedef jshortArray = jarray;
typedef jsize = jint;
typedef jstring = jobject;
typedef jthrowable = jobject;
typedef jweak = jobject;

sealed class media_status_t {
  static const AMEDIA_OK = 0;
  static const AMEDIACODEC_ERROR_INSUFFICIENT_RESOURCE = 1100;
  static const AMEDIACODEC_ERROR_RECLAIMED = 1101;
  static const AMEDIA_ERROR_BASE = -10000;
  static const AMEDIA_ERROR_UNKNOWN = -10000;
  static const AMEDIA_ERROR_MALFORMED = -10001;
  static const AMEDIA_ERROR_UNSUPPORTED = -10002;
  static const AMEDIA_ERROR_INVALID_OBJECT = -10003;
  static const AMEDIA_ERROR_INVALID_PARAMETER = -10004;
  static const AMEDIA_ERROR_INVALID_OPERATION = -10005;
  static const AMEDIA_ERROR_END_OF_STREAM = -10006;
  static const AMEDIA_ERROR_IO = -10007;
  static const AMEDIA_ERROR_WOULD_BLOCK = -10008;
  static const AMEDIA_DRM_ERROR_BASE = -20000;
  static const AMEDIA_DRM_NOT_PROVISIONED = -20001;
  static const AMEDIA_DRM_RESOURCE_BUSY = -20002;
  static const AMEDIA_DRM_DEVICE_REVOKED = -20003;
  static const AMEDIA_DRM_SHORT_BUFFER = -20004;
  static const AMEDIA_DRM_SESSION_NOT_OPENED = -20005;
  static const AMEDIA_DRM_TAMPER_DETECTED = -20006;
  static const AMEDIA_DRM_VERIFY_FAILED = -20007;
  static const AMEDIA_DRM_NEED_KEY = -20008;
  static const AMEDIA_DRM_LICENSE_EXPIRED = -20009;
  static const AMEDIA_IMGREADER_ERROR_BASE = -30000;
  static const AMEDIA_IMGREADER_NO_BUFFER_AVAILABLE = -30001;
  static const AMEDIA_IMGREADER_MAX_IMAGES_ACQUIRED = -30002;
  static const AMEDIA_IMGREADER_CANNOT_LOCK_IMAGE = -30003;
  static const AMEDIA_IMGREADER_CANNOT_UNLOCK_IMAGE = -30004;
  static const AMEDIA_IMGREADER_IMAGE_NOT_LOCKED = -30005;
}

typedef ssize_t = __kernel_ssize_t;
typedef va_list = __builtin_va_list;
